spring.datasource.url=${DB_URL:jdbc:mysql://localhost/projetopoo?createDatabaseIfNotExist=true&serverTimezone=UTC}

spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234567}

spring.jpa.show-sql=true

